### PR TITLE
Win32 update bindings

### PR DESCRIPTION
**Pull request by vvuk**
The only commit from here that actually matters is the "Use visibility attributes eveno windows when running rust bindgen" -- might want to just take that one.  The others are generic win32 stuff that are also in my win32 branch that may land sooner.

### CODE REVIEW

**Comment by michaelwu** [comment]
@tschneidereit FYI

For the visibility patch, I suspect this may be a clang issue since it should handle dllexport.

**Comment by michaelwu** [comment]
For the record - the visibility issue is fixed by `-DEXPORT_JS_API=1`, which makes sure we use dllexport instead of dllimport.

**Comment by tschneidereit** [comment]
> For the record - the visibility issue is fixed by -DEXPORT_JS_API=1, which makes sure we use dllexport instead of dllimport.

Ah, nice. While we can certainly land rust-specific stuff upstream, it's nice to avoid it if possible.

**Comment by vvuk** [comment]
Closing this to reopen in servo/mozjs

**Pull request closed without merging**
